export const APPLICATION_LIST = "APPLICATION_LIST";
export const THEME_COLOR = "THEME_COLOR";
export const APPLICATION_ELEMENTS = "APPLICATION_ELEMENTS";
export const IS_LOGIN_PAGE = "IS_LOGIN_PAGE";
